// This file is generated by tools/gen_types.py from contract/app.schema.json.
// Do not edit it by hand: change the schema and run
//   python3 tools/gen_types.py
// The schema's $defs, sorted by name, as one value: the guard src/validate.ts
// checks the server's answers against, so the page trusts the whole view.

export const DEFS = {
  "Answer": {
    "additionalProperties": false,
    "properties": {
      "message": {
        "type": "string"
      },
      "notes": {
        "items": {
          "$ref": "#/$defs/Note"
        },
        "type": "array"
      },
      "ok": {
        "type": "boolean"
      }
    },
    "required": [
      "ok",
      "notes",
      "message"
    ],
    "type": "object"
  },
  "Note": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "type": "string"
      },
      "text": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "text"
    ],
    "type": "object"
  },
  "NoteCommand": {
    "oneOf": [
      {
        "additionalProperties": false,
        "properties": {
          "kind": {
            "enum": [
              "add"
            ]
          },
          "text": {
            "type": "string"
          }
        },
        "required": [
          "kind",
          "text"
        ],
        "type": "object"
      },
      {
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "remove"
            ]
          }
        },
        "required": [
          "kind",
          "id"
        ],
        "type": "object"
      }
    ]
  },
  "NotesView": {
    "additionalProperties": false,
    "properties": {
      "notes": {
        "items": {
          "$ref": "#/$defs/Note"
        },
        "type": "array"
      },
      "role": {
        "enum": [
          "listener",
          "member",
          "admin"
        ]
      }
    },
    "required": [
      "notes",
      "role"
    ],
    "type": "object"
  }
} as const;
