// This file is generated by tools/gen_types.py from contract/app.schema.json.
// Do not edit it by hand: change the schema and run
//   python3 tools/gen_types.py
// One type per $defs entry, sorted by name, then Routes: every route the page
// calls, keyed by method and path, with its body and response type, and for a GET
// its query and path parameters, and `bytes: true` where it answers a file.

export type Answer = {
  readonly ok: boolean;
  readonly notes: ReadonlyArray<Note>;
  readonly message: string;
};

export type Note = {
  readonly id: string;
  readonly text: string;
};

export type NoteCommand =
  | {
      readonly kind: "add";
      readonly text: string;
    }
  | {
      readonly kind: "remove";
      readonly id: string;
    };

export type NotesView = {
  readonly notes: ReadonlyArray<Note>;
  readonly role: "listener" | "member" | "admin";
};

export type Routes = {
  readonly "GET /api/notes": {
    readonly query: null;
    readonly params: null;
    readonly body: null;
    readonly response: NotesView;
  };
  readonly "POST /api/notes": {
    readonly body: NoteCommand;
    readonly response: Answer;
  };
};
