"""Generate the page's TypeScript contract from contract/app.schema.json.

Two files come from the one schema document. `src/contract.gen.ts` holds the types:
one TypeScript type per `$defs` entry (readonly object fields, `T | null` where the
schema allows null, a string-literal union for an enum, `ReadonlyArray<T>` for an
array, and a union for a `oneOf` command), then `Routes`, the schema's `routes`
table, one member per route keyed by method and path. A POST member carries the body
and response its entry names; a GET member also carries `query` (the object it
accepts, or null) and `params` (the route key's `{name}` placeholders as a readonly
object, or null), and a route that answers a file carries `bytes: true` beside a
null response. `src/contract.schema.gen.ts` holds the schema's `$defs` itself as one
`export const DEFS = {...} as const`, which `src/validate.ts` checks the store's
events against. Both are emitted sorted by name, so the output is deterministic.

`--check` writes neither file and exits 1 when one on disk differs, so the
template's `.dark/verify.sh` fails on a stale file. Standard library only: the
subset of JSON Schema the schema uses is small enough to read directly, and a
generator that pulled in a codegen dependency would be a new dependency for one
file.

Run: python3 tools/gen_types.py [--check] [--schema PATH] [--out PATH] [--defs-out PATH]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "contract" / "app.schema.json"
TYPES_PATH = ROOT / "src" / "contract.gen.ts"
DEFS_PATH = ROOT / "src" / "contract.schema.gen.ts"

WIDTH = 80
"""The line width the output aims at, so a formatter has nothing to wrap."""

_PARAM = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")
"""A route path's `{name}` placeholder, the same shape api.ts fills at run time."""

HEADER = """\
// This file is generated by tools/gen_types.py from contract/app.schema.json.
// Do not edit it by hand: change the schema and run
//   python3 tools/gen_types.py
// One type per $defs entry, sorted by name, then Routes: every route the page
// calls, keyed by method and path, with its body and response type, and for a GET
// its query and path parameters, and `bytes: true` where it answers a file."""

DEFS_HEADER = """\
// This file is generated by tools/gen_types.py from contract/app.schema.json.
// Do not edit it by hand: change the schema and run
//   python3 tools/gen_types.py
// The schema's $defs, sorted by name, as one value: the guard src/validate.ts
// checks the server's answers against, so the page trusts the whole view."""

_TS_NAMES = {
    "string": "string",
    "number": "number",
    "integer": "number",
    "boolean": "boolean",
    "null": "null",
}


def load_schema(path: Path) -> dict[str, Any]:
    """The schema document, parsed."""
    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError(f"{path} is not a JSON object")
    return document


def generate(schema: dict[str, Any]) -> str:
    """The whole generated file for one schema document."""
    defs = schema.get("$defs")
    if not isinstance(defs, dict) or not defs:
        raise ValueError("the schema has no $defs")
    blocks = [HEADER]
    for name in sorted(defs):
        definition = defs[name]
        if not isinstance(definition, dict):
            raise ValueError(f"$defs/{name} is not a schema object")
        blocks.append(_alias(name, definition))
    routes = schema.get("routes")
    if isinstance(routes, dict) and routes:
        blocks.append(_routes(routes))
    return "\n\n".join(blocks) + "\n"


def generate_defs(schema: dict[str, Any]) -> str:
    """The schema's `$defs` as one `export const DEFS = {...} as const`."""
    defs = schema.get("$defs")
    if not isinstance(defs, dict) or not defs:
        raise ValueError("the schema has no $defs")
    ordered = {name: defs[name] for name in sorted(defs)}
    body = json.dumps(ordered, indent=2, ensure_ascii=False, sort_keys=True)
    return f"{DEFS_HEADER}\n\nexport const DEFS = {body} as const;\n"


def _routes(routes: dict[str, Any]) -> str:
    """The `Routes` table: one member per route, sorted by key.

    A GET member also carries `query` (the object it accepts, or null), `params`
    (the `{name}` placeholders of its path as one readonly object, or null) and,
    when the route answers bytes, `bytes: true` beside a null response. A POST
    member keeps the body and response the schema wrote.
    """
    lines = ["export type Routes = {"]
    for key in sorted(routes):
        entry = routes[key]
        if not isinstance(entry, dict):
            raise ValueError(f"routes/{key} is not a schema object")
        body = entry.get("body")
        body_type = "null" if body is None else _type(body)
        response = entry.get("response")
        is_bytes = entry.get("bytes") is True
        if response is None:
            if not is_bytes:
                raise ValueError(f"routes/{key} names no response")
            response_type = "null"
        else:
            response_type = _type(response)
        lines.append(f"  readonly {json.dumps(key)}: {{")
        if "query" in entry:
            query = entry["query"]
            query_type = "null" if query is None else _type(query)
            lines.append(f"    readonly query: {query_type};")
            lines.append(f"    readonly params: {_params_type(key)};")
        lines.append(f"    readonly body: {body_type};")
        lines.append(f"    readonly response: {response_type};")
        if is_bytes:
            lines.append("    readonly bytes: true;")
        lines.append("  };")
    lines.append("};")
    return "\n".join(lines)


def _params_type(key: str) -> str:
    """A route key's `{name}` placeholders as one readonly object, or `null`."""
    names = list(dict.fromkeys(_PARAM.findall(key)))
    if not names:
        return "null"
    fields = " ".join(f"readonly {name}: string;" for name in names)
    return "{ " + fields + " }"


def _alias(name: str, node: dict[str, Any]) -> str:
    """One `export type <name> = ...;`, wrapped when a union will not fit."""
    line = f"export type {name} = {_type(node)};"
    if len(line) <= WIDTH:
        return line
    parts = _union_parts(node)
    if len(parts) < 2:
        return line
    lines = [f"export type {name} ="]
    for part in parts:
        member = part.split("\n")
        lines.append(f"  | {member[0]}")
        lines.extend(f"    {line}" for line in member[1:])
    return "\n".join(lines) + ";"


def _type(node: object) -> str:
    """The TypeScript type for one schema node."""
    if not isinstance(node, dict):
        raise ValueError("a schema node is not an object")
    if "$ref" in node:
        return _ref_name(node["$ref"])
    parts = _union_parts(node)
    if parts:
        return " | ".join(parts)
    types = node.get("type")
    if types == "array":
        return _array(node)
    if types == "object" or "properties" in node or "additionalProperties" in node:
        return _object(node)
    if isinstance(types, str):
        return _ts_name(types)
    raise ValueError(f"this generator cannot render a node with {sorted(node)}")


def _union_parts(node: dict[str, Any]) -> list[str]:
    """The members of a union node (enum, oneOf or a type list), or [] for one type."""
    if isinstance(node.get("enum"), list):
        return [json.dumps(value) for value in node["enum"]]
    if isinstance(node.get("oneOf"), list):
        return [_type(part) for part in node["oneOf"]]
    types = node.get("type")
    if isinstance(types, list):
        return [_ts_name(str(name)) for name in types]
    return []


def _object(node: dict[str, Any]) -> str:
    """One object type: a literal with readonly fields, or a string-keyed record."""
    properties = node.get("properties")
    if not isinstance(properties, dict) or not properties:
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Readonly<Record<string, {_type(extra)}>>"
        return "Readonly<Record<string, never>>"
    required = node.get("required")
    needed = set(required) if isinstance(required, list) else set()
    lines = ["{"]
    for key, value in properties.items():
        mark = "" if key in needed else "?"
        lines.append(f"  readonly {key}{mark}: {_type(value)};")
    lines.append("}")
    return "\n".join(lines)


def _array(node: dict[str, Any]) -> str:
    items = node.get("items")
    inner = _type(items) if isinstance(items, dict) else "never"
    return f"ReadonlyArray<{inner}>"


def _ts_name(name: str) -> str:
    mapped = _TS_NAMES.get(name)
    if mapped is None:
        raise ValueError(f"no TypeScript name for the JSON type {name!r}")
    return mapped


def _ref_name(ref: object) -> str:
    text = str(ref)
    prefix = "#/$defs/"
    if not text.startswith(prefix):
        raise ValueError(f"this generator knows only #/$defs refs, not {text!r}")
    return text[len(prefix) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the TypeScript contract")
    parser.add_argument("--check", action="store_true", help="exit 1 when a file is stale")
    parser.add_argument("--schema", type=Path, default=SCHEMA_PATH)
    parser.add_argument("--out", type=Path, default=TYPES_PATH, help="where the types go")
    parser.add_argument("--defs-out", type=Path, default=DEFS_PATH, help="where DEFS go")
    args = parser.parse_args(argv)
    schema = load_schema(args.schema)
    outputs = [(args.out, generate(schema)), (args.defs_out, generate_defs(schema))]
    if args.check:
        stale = False
        for path, text in outputs:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != text:
                print(f"{path} is stale; run: python3 tools/gen_types.py", file=sys.stderr)
                stale = True
        return 1 if stale else 0
    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
